# -*- coding: utf-8 -*-
"""healthcare 2 part -B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bii557sDCC9YCnqh1xhUMpLvnqA2ZPW7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/healthcare_dataset (1).csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Year_Month'] = df['Date of Admission'].dt.to_period('M')

monthly_admissions = df.groupby('Year_Month').size()

monthly_admissions.head()

peak_month = monthly_admissions.idxmax()
peak_admissions = monthly_admissions.max()

print("Peak Admission Month:", peak_month)
print("Number of Admissions:", peak_admissions)

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

import matplotlib.pyplot as plt
plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Average Billing Amount by Medical Condition:")
print(df.groupby('Medical Condition')['Billing Amount'].mean())

print("\nAverage Billing Amount by Insurance Provider:")
print(df.groupby('Insurance Provider')['Billing Amount'].mean())

df ['Admission Month']=df['Date of Admission'].dt.month
df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(12, 6))
monthly_admissions.plot(kind="line",marker="o")
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid()
plt.show()

df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Stay Duration'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
correlation_matrix = df[["Age", "Stay Duration", "Billing Amount"]].corr()
correlation_matrix

sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""Summary:-


Billing Amount by Medical Condition & Insurance Provider (Bar Chart)
Different medical conditions and insurance providers have different billing amounts.
Some condition–insurance combinations show higher healthcare costs than others.
Billing Amount Distribution by Medical Condition (Violin Plot)
Shows how billing amounts vary for each medical condition.
Some conditions have a wider range of treatment costs.
Billing Amount Distribution by Insurance Provider (Violin Plot)
Compares billing amount distributions across insurance providers.
Certain providers have higher or more varied claim amounts.
Monthly Admissions Trend (Line Graph)
Displays the number of patient admissions each month.
Helps identify months with higher or lower hospital admissions.
Correlation Matrix (Heatmap)
Shows relationships between numerical variables in the dataset.
Stronger colors indicate stronger positive or negative correlations between variables.
"""

