# -*- coding: utf-8 -*-
"""Apple Stock

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfZ7kUP_pXwD1EfgpKupy6VftT1W3Pxw
"""

!pip install pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/AAPL.xlsx")
df

df.head()

df.tail()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")
print(df[["Date"]].head(10))

df["Daily Price Change"] = df["Close"].diff()
print(df[["Daily Price Change"]].head(10))

df["Daily Return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100
print(df[["Daily Return"]].head(10))

print(df.head(10))

print("\nStock Price Analysis:")
print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

df["Daily Percentage Change"] = (df["Daily Price Change"] / df["Close"].shift(1)) * 100
print("\nDaily Price Change:")
print(df[["Date", "Close", "Daily Price Change", "Daily Percentage Change"]])

df

#line chart view
plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print(df[["Date", "Close", "Daily Percentage Change"]])

biggest_losses = df.sort_values(by='Daily Percentage Change').head()
print("\nDays with Biggest Losses:")
print(biggest_losses[["Date", "Close", "Daily Percentage Change"]])

print("\nTrading Volume Analysis (Recap):")
print("Average Volume:", df["Volume"].mean())
print("Minimum Volume:", df["Volume"].min())
print("Maximum Volume:", df["Volume"].max())

highest_volume_days = df.sort_values(by='Volume', ascending=False).head(10)
print("\nTop 10 Days with Highest Trading Volume:")
print(highest_volume_days[["Date", "Volume", "Close"]])