# -*- coding: utf-8 -*-
"""Shopify Stock

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axEJLZ6QnL3l0HQvaplpXqZasUSr3Wdj
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('shopify_stock.csv')
display(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
df['date'] = pd.to_datetime(df['date'], utc=True)

plt.figure(figsize=(15, 7))
sns.lineplot(data=df, x='date', y='close')
plt.title('Shopify Stock Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price (USD)')
plt.grid(True)
plt.show()

df['MA20'] = df['close'].rolling(window=20).mean()
df['MA50'] = df['close'].rolling(window=50).mean()

plt.figure(figsize=(15, 7))
sns.lineplot(data=df, x='date', y='close', label='Closing Price')
sns.lineplot(data=df, x='date', y='MA20', label='20-Day Moving Average')
sns.lineplot(data=df, x='date', y='MA50', label='50-Day Moving Average')

plt.title('Shopify Stock Closing Price with 20 & 50 Day Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid(True)
plt.show()

df['Daily_Return'] = df['close'].pct_change() * 100
display(df.head())

plt.figure(figsize=(12, 6))
sns.histplot(df['Daily_Return'].dropna(), bins=50, kde=True, color='skyblue')
plt.title('Distribution of Shopify Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()





